Compact list
dracidoupe/graveyard pull request #359
Opened 2021-08-15 09:32 UTC by jimmeak

2021-08-15 10:24 UTC, Almad commented
`Skupiny` are not working in some cases (like Articles or Warrior)

<img width="793" alt="image" src="https://user-images.githubusercontent.com/44565/129475300-e7e98a15-07e8-4b88-88dd-17045eb72761.png">

I'd also maybe add more creations per page in those cases 🤔

2021-08-15 10:26 UTC, Almad commented
I think the singular idea doesn't make sense in this context, the correct name for the column is just "Name". 

Or do you think the "Válečník" column above makes sense? IMHO it only goes for "Článek" in ČaE, somewhat.

2021-08-15 10:32 UTC, Almad requested changes
I just wonder—instead of doing template tag, wouldn't it be better to remove all `-list` templates and have one generic `creations-list` one? I don't think there is now something creation-specific left in all except (photo)gallery/download anyway, or is it?

2021-08-15 10:32 UTC, Almad commented on ddcz/templatetags/pages.py
> +    print("\n\n\n\n")
Leftover?

2021-08-15 10:32 UTC, Almad commented on ddcz/templatetags/creations.py
> +    return CreativePage.objects.get(slug=slug).singular_name
This is unnecessary additional query since you can pass a creative page from view where you already have it

2021-08-15 10:36 UTC, jimmeak commented
> I think the singular idea doesn't make sense in this context, the correct name for the column is just "Name".
> 
> Or do you think the "Válečník" column above makes sense? IMHO it only goes for "Článek" in ČaE, somewhat.

@Almad Of course, just like this it is not good, but I had the name before and e. g. `Hřbitov` is not very good either. That's why I wanted to make something more suitable exactly for this heading.

2021-08-15 10:37 UTC, jimmeak commented on ddcz/templatetags/pages.py
> +    print("\n\n\n\n")
yup, thanks :)

2021-08-15 10:37 UTC, jimmeak commented
> I just wonder—instead of doing template tag, wouldn't it be better to remove all `-list` templates and have one generic `creations-list` one? I don't think there is now something creation-specific left in all except (photo)gallery/download anyway, or is it?

I believe so, but I didn't want to destroy it all before asking first. :)

2021-08-15 11:15 UTC, Almad commented
@jimmeak 

> I believe so, but I didn't want to destroy it all before asking first. :)

Nuke it from orbit! :) 

> Of course, just like this it is not good, but I had the name before and e. g. Hřbitov is not very good either. That's why I wanted to make something more suitable exactly for this heading.

How about "Jméno"? It also removes the need for singular, which I think doesn't make sense on the CreativePage model anyway—it should be on the particular Creations model.

2021-08-22 17:40 UTC, jimmeak commented
> How about "Jméno"? It also removes the need for singular, which I think doesn't make sense on the CreativePage model anyway—it should be on the particular Creations model.

I went for a "Název", it seems better for creations than name.

2021-08-22 18:20 UTC, jimmeak commented
> Nuke it from orbit! :)

Done, but it still will need some gallery and those special lists to edit, I think we have another issues for it (I believe for @Wynnka :smile: )

2021-09-04 09:47 UTC, Almad commented
To be rebased & sent to master

2021-09-04 09:47 UTC, closed without merging